### ISSUE TITLE
Cannot install it

### ISSUE THREAD

**Issue by kevnmr** [sburns/recon-stats#6]
Hi

Thank you for this awesome package. I'm trying to install this package i did:

1. git clone https:etc...
2. sudo python setup.py install
however getting error:
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from recon_stats import __version__
  File "/home/kevin/Downloads/recon-stats/recon_stats/__init__.py", line 15, in <module>
    from .core import Subject
  File "/home/kevin/Downloads/recon-stats/recon_stats/core.py", line 26
    raise ValueError(f"This subject doesn't have a 'stats' dir at {self.stat_dir}")

I'm on python Python 2.7.13.

Thank you for any help.

Kevin

**Comment by sburns** [comment]
This package is no longer compatible with python2, you should consider upgrading to python 3 if possible of python2's end-of-life is january 1, 2020.

**Comment by kevnmr** [comment]
Hi Sir 

Sorry but tried with python 3.5.5 still getting same error:

raceback (most recent call last):
  File "setup.py", line 7, in <module>
    from recon_stats import __version__
  File "/home/brain/Downloads/recon-stats/recon_stats/__init__.py", line 15, in <module>
    from .core import Subject
  File "/home/brain/Downloads/recon-stats/recon_stats/core.py", line 26
    raise ValueError(f"This subject doesn't have a 'stats' dir at {self.stat_dir}")
                                                                                 ^
SyntaxError: invalid syntax
brain@ubuntu:~/Downloads/recon-stats$ python -V
Python 3.5.5 :: Anaconda custom (64-bit)
brain@ubuntu:~/Downloads/recon-stats$

Any help would be greatly appreciated.

Kevin

**Comment by sburns** [comment]
Sorry, we're using specific 3.6 features.
